const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store"}});
const cookie=(name,val,maxAge)=>`${name}=${val}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;
async function hash(p){const b=new TextEncoder().encode(p),k=await crypto.subtle.importKey("raw",b,{name:"PBKDF2"},false,["deriveBits"]);const salt=crypto.getRandomValues(new Uint8Array(16));const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:120000,hash:"SHA-256"},k,256);return `${b64(salt)}.${b64(new Uint8Array(bits))}`}
async function verify(p,stored){const [ss,hh]=stored.split('.'),salt=ub64(ss),b=new TextEncoder().encode(p),k=await crypto.subtle.importKey("raw",b,{name:"PBKDF2"},false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:120000,hash:"SHA-256"},k,256);return b64(new Uint8Array(bits))===hh}
function b64(a){return btoa(String.fromCharCode(...a)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function ub64(s){s=s.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function token(){return b64(crypto.getRandomValues(new Uint8Array(32)))}
function getSid(req){return (req.headers.get('Cookie')||'').match(/sid=([^;]+)/)?.[1]}
async function user(req,env){const sid=getSid(req);if(!sid)return null;return await env.DB.prepare("SELECT u.id,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?").bind(sid,Date.now()).first()}
function cleanEmail(e){return String(e||'').trim().toLowerCase()}
export default {async fetch(req,env){const url=new URL(req.url);try{
if(url.pathname.startsWith('/api/')) return await api(req,env,url);
return env.ASSETS.fetch(req)
}catch(e){return json({error:"Server error"},500)}}}
async function api(req,env,url){
const path=url.pathname, method=req.method;
if(path==='/api/register'&&method==='POST'){const {email,password}=await req.json();const e=cleanEmail(email);if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e)||String(password).length<8)return json({error:"Email tidak valid atau password kurang dari 8 karakter."},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(e).first())return json({error:"Email sudah terdaftar."},409);const h=await hash(password),id=crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,email,password_hash,created_at) VALUES(?,?,?,?)").bind(id,e,h,Date.now()).run();const sid=token();await env.DB.prepare("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)").bind(sid,id,Date.now()+2592000000).run();return new Response(JSON.stringify({ok:true}),{headers:{"content-type":"application/json","set-cookie":cookie('sid',sid,2592000)}})}
if(path==='/api/login'&&method==='POST'){const {email,password}=await req.json();const u=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(cleanEmail(email)).first();if(!u||!(await verify(password,u.password_hash)))return json({error:"Email atau password salah."},401);const sid=token();await env.DB.prepare("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)").bind(sid,u.id,Date.now()+2592000000).run();return new Response(JSON.stringify({ok:true}),{headers:{"content-type":"application/json","set-cookie":cookie('sid',sid,2592000)}})}
if(path==='/api/logout'&&method==='POST'){const sid=getSid(req);if(sid)await env.DB.prepare("DELETE FROM sessions WHERE token=?").bind(sid).run();return new Response(JSON.stringify({ok:true}),{headers:{"content-type":"application/json","set-cookie":cookie('sid','',0)}})}
if(path==='/api/me'){return json({user:await user(req,env)})}
if(path==='/api/listings'&&method==='GET'){const q=url.searchParams.get('q')||'',c=url.searchParams.get('category')||'',sort=url.searchParams.get('sort')||'new';let sql="SELECT l.id,l.title,l.category,l.price,l.image,l.wa,l.description,l.rank,l.level,l.skins,u.email seller FROM listings l JOIN users u ON u.id=l.user_id WHERE l.status='active'",a=[];if(q){sql+=" AND (l.title LIKE ? OR l.description LIKE ?)";a.push('%'+q+'%','%'+q+'%')}if(c){sql+=" AND l.category=?";a.push(c)}sql+=sort==='low'?" ORDER BY l.price ASC, l.created_at DESC":sort==='high'?" ORDER BY l.price DESC, l.created_at DESC":" ORDER BY l.created_at DESC";sql+=" LIMIT 100";const {results}=await env.DB.prepare(sql).bind(...a).all();return json({listings:results})}
if(path==='/api/listings'&&method==='POST'){const u=await user(req,env);if(!u)return json({error:"Silakan masuk terlebih dahulu."},401);const x=await req.json();const title=String(x.title||'').trim(),category=String(x.category||''),price=Number(x.price),image=String(x.image||'').trim(),wa=String(x.wa||'').replace(/\D/g,''),description=String(x.description||'').trim(),rank=String(x.rank||'').trim(),level=Math.max(0,Math.floor(Number(x.level)||0)),skins=Math.max(0,Math.floor(Number(x.skins)||0));const games=['Free Fire','Mobile Legends','PUBG Mobile','Valorant','Roblox','Genshin Impact','Game Lainnya'];if(title.length<3||title.length>120||!games.includes(category)||!Number.isFinite(price)||price<0||!wa)return json({error:"Data listing belum lengkap atau tidak valid."},400);const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO listings(id,user_id,title,category,price,image,wa,description,rank,level,skins,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,u.id,title,category,Math.round(price),image,wa,description,rank,level,skins,'active',Date.now()).run();return json({ok:true,id},201)}
return json({error:"Not found"},404)}
